---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp
  namespace: jenkins
  labels:
    app: javawebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
        - name: javawebapp
          image: pritiswami123/deployapp:latest  # Correct image name and tag
          imagePullPolicy: always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappservice
spec:
  selector:
    app: javawebapp
  ports:
    - protocol: "TCP"
      port: 9191      # The port your Spring Boot app listens on
      targetPort: 9191
      nodePort: 30080  # The port on the host to access the app
  type: NodePort





