apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: DeployApp
spec:
  selector:
    matchLabels:
      app: DeployApp
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: DeployApp
    spec:
      containers:
        - name: DeployApp
          image: pritiswami123/deployapp  # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: DeployApp-k8ssvc
spec:
  selector:
    app: DeployApp
  ports:
    - protocol: "TCP"
      port: 9191 # The port that the service is running on in the cluster
      targetPort: 9191 # The port exposed by the service
  type: NodePort # type of the service.